### ISSUE TITLE
优化自定义元信息的覆盖范围

### ISSUE THREAD

**Issue by Fs-DXMY** [ccmjga/mjga-scaffold#10]
### 可优化点

当自定义元信息的任意属性均不包含 `mjga` 字样时，下载的生成产物依然包含大量 `mjga`，需要手动修改。

例如 `.env`、`gradle.properties`、`Dockerfile`、初始化 SQL 脚本、测试用例等。

### 图示

![env](https://github.com/user-attachments/assets/e29d4542-c48d-4665-b7f8-e342ccc7e6b0)
![gradle properties](https://github.com/user-attachments/assets/2a13e4dd-4dc5-4313-ae83-4138390991a7)

**Comment by ccmjga** [comment]
2.7.2 已修复
