### ISSUE TITLE
去除测试代码中的固定数据库名

### ISSUE THREAD

**Issue by zhaoxuanyi** [ccmjga/mjga-scaffold#11]
**Your OS & Cpu Architecture**
MacOS/x86

**Soft Version**
2.2

**Your template name**
Database First

**Describe the bug**
1. 测试代码中的固定数据库 mjga. 前缀去除
org.testcontainers.containers.MySQLContainer#withDatabaseName
3. ...
4. ...

**Expected behavior**

**Others**

**Comment by zhaoxuanyi** [comment]
build.gradle.kts 也硬编码了数据库名
org.jooq.meta.jaxb.Database#setInputSchema

**Comment by ccmjga** [comment]
该问题整合到
https://github.com/ccmjga/mjga-scaffold/issues/10
