### ISSUE TITLE
[Bug] 自定义元数据时，`Done` 按钮概率无法点击

### ISSUE THREAD

**Issue by Fs-DXMY** [ccmjga/mjga-scaffold#12]
## 问题描述

部分场景下，即使所有输入框内均为合法值，`Done` 按钮依然无法点击：

![Done无法点击](https://github.com/user-attachments/assets/04131faf-8cde-4aed-9f89-07211e1210f9)

## 排查方向

怀疑为字段校验逻辑出现了问题。

以 `Artifact` 输入框为例，当输入 `'` 字符或长数字后，`Done` 置灰无法点击。但修改为合法值后，置灰并未恢复。

**Comment by ccmjga** [comment]
https://github.com/ccmjga/mjga-scaffold/releases/tag/v2.9.0
