### ISSUE TITLE
基于mysql初始化异常

### ISSUE THREAD

**Issue by visla-perlin** [ccmjga/mjga-scaffold#13]
**Your OS & Cpu Architecture**
Windows11

**Soft Version**
2.2

**Your template name**
Database First

**Describe the bug**
1. 选择mysql模板，初始化创建table无法通过，看错误是包含了引号
2. db的database name(qinxin-api)和 项目配置的name(api)不一致时，无法使用查询语句
3. 不支持基于db名称的初始化
![image](https://github.com/user-attachments/assets/aba1b9fd-8871-4568-bf59-d60beb0be015)

![image](https://github.com/user-attachments/assets/38237f41-72cb-497f-8470-7e5f67899132)

**Comment by ccmjga** [comment]
1. 选择mysql模板，初始化创建table无法通过，看错误是包含了引号 -> 该问题已经修复完毕
2. db的database name(qinxin-api)和 项目配置的name(api)不一致时，无法使用查询语句
3. 不支持基于db名称的初始化


2 和 3 的问题我不明白，能够详细描述一下吗？

**Comment by ccmjga** [comment]
问题 1 已修复了。
问题 2 和 3 我大概明白你的意思了。

目前 database name 是根据你填入的 Name 这个字端来动态变化的。如果你在下载后项目后，还要修改 database name 这种属于完全的自定义行为，这种就需要你自己去修改对应的内容。
基于 db 名称初始化的功能后续可以考虑，目前暂时不支持。你可以提一个单独的 ehancement 挂在那里，将来有时间可以考虑实现。
