### ISSUE TITLE
pmd 自定义规则集下 gradle 警告 RuleSet description is missing. Future versions of PMD will require it.

### ISSUE THREAD

**Issue by cbq1024** [ccmjga/mjga-scaffold#3]
如题当通过： ruleSetFiles = files("pmd-rules.xml") 这种方式加载 pmd 的规则集的时候我遇到了问题 

version:

- jdk zulu-21
- gradle 8.10

下面是 gradle 配置

```kts
pmd {
    isConsoleOutput = true
    isIgnoreFailures = false
    toolVersion = "7.5.0"
    rulesMinimumPriority.set(5)
    ruleSetFiles = files("pmd-rules.xml")
}
```

报错信息：

![Snipaste_2024-10-05_17-42-07](https://github.com/user-attachments/assets/a74d2f68-a6fc-4c10-bc2f-72fc4104a0e2)

这是我的 pmd-rules.xml 文件 

```xml
<?xml version="1.0"?>
<ruleset name="Custom Rules"
         xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

    <rule ref="category/java/bestpractices.xml">
        <exclude name="GuardLogStatement"/>
    </rule>
    <rule ref="category/java/errorprone.xml">
        <exclude name="AvoidLiteralsInIfCondition"/>
    </rule>

</ruleset>

```

其中的 http://pmd.sourceforge.net/ruleset/2.0.0 访问提示 

![Snipaste_2024-10-05_17-43-01](https://github.com/user-attachments/assets/49da10f2-cf5b-4f32-84b7-57805ad51242)

我通过查询 pmd 官网发现其提供的 xml 文件模板也是 `http://pmd.sourceforge.net/ruleset/2.0.0`  我不确定这是哪方面的错误但我发现一种解决方案(在 gradle 配置中手动指定规则集)：

```kts
pmd {
    isConsoleOutput = true
    isIgnoreFailures = false
    toolVersion = "7.5.0"
    rulesMinimumPriority.set(5)
    ruleSets = listOf("category/java/errorprone.xml", "category/java/bestpractices.xml")
}
```

![Snipaste_2024-10-05_17-46-03](https://github.com/user-attachments/assets/e44ee77c-f39c-48ce-a48c-057193fa8db7)

![Snipaste_2024-10-05_17-46-09](https://github.com/user-attachments/assets/84e0ac9a-6d93-43fe-8975-962aca93700b)

**Comment by cbq1024** [comment]
> 

> 如题当通过： ruleSetFiles = files("pmd-rules.xml") 这种方式加载 pmd 的规则集的时候我遇到了问题
> 
> 下面是 gradle 配置
> 
> ```kotlin
> pmd {
>     isConsoleOutput = true
>     isIgnoreFailures = false
>     toolVersion = "7.5.0"
>     rulesMinimumPriority.set(5)
>     ruleSetFiles = files("pmd-rules.xml")
> }
> ```
> 
> 报错信息：
> 
> ![Snipaste_2024-10-05_17-42-07](https://private-user-images.githubusercontent.com/183713411/373862044-a74d2f68-a6fc-4c10-bc2f-72fc4104a0e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjIxODMsIm5iZiI6MTcyODEyMTg4MywicGF0aCI6Ii8xODM3MTM0MTEvMzczODYyMDQ0LWE3NGQyZjY4LWE2ZmMtNGMxMC1iYzJmLTcyZmM0MTA0YTBlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwOTUxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDk0MjY3MTc1YWYxOTI4ZWUwYjYxNGUzZTkwYzE1ZDVlNTBlNWEzYzU1OGVkZmZlZjY5NDY3YTZhNDkzMzI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eM2ZYOUiQ4brSC7CbwfJLv63zYpbuxe7DOg6xLg-HJI)

抱歉该情况下 pmd 仍然是正常工作的但是我很好奇如何修正下面的警告(通过手动指定规则确实不会出现该警告)

```xml
Warning at C:\Users\cbq1024\IdeaProjects\how-spring-boot3\pmd-rules.xml:2:1
 1| <?xml version="1.0"?>
 2| <ruleset name="Custom Rules"
    ^^^^^^^^ RuleSet description is missing. Future versions of PMD will require it.

 3|          xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
 4|          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
```

**Comment by ccmjga** [comment]
2.7.2 版本修复了这个远古问题。
