### ISSUE TITLE
web The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s

### ISSUE THREAD

**Issue by mr-dragon** [ccmjga/mjga-scaffold#4]
## 问题Q：web The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s

A：指定运行的架构平台为ARM64，默认是AMD。

```dockerfile
#这个镜像有arm版的，会自动选择，不用指定也行：--platform=linux/arm64
FROM --platform=linux/arm64 gradle:8.10.0-jdk21-alpine AS builder

# https://hub.docker.com/r/alpine/java/tags Currently only support platform linux/amd64 不支持arm64
#FROM alpine/java:21-jdk AS RUNNER
# 主要是jdk要换成这个 https://hub.docker.com/_/eclipse-temurin/tags?name=21-jdk-alpine
# 换完自己会使用arm64架构的版本。
FROM eclipse-temurin:21-jdk-alpine AS RUNNER

```

### --platform=linux/arm64

- --platform=linux/arm64 指定了 ARM64 架构的 Linux 平台。这适用于:
	- Apple M1/M2 ……系 芯片的 Mac 电脑
	- 一些基于 ARM 的服务器(如 AWS Graviton)
	- 某些 ARM 架构的开发板

**Comment by mr-dragon** [comment]
docker compose build web
docker compose up -d web

**Comment by ccmjga** [comment]
感谢报告问题。
目前 2.3 版本已经更换为了
`eclipse-temurin:17-jdk-alpine & eclipse-temurin:21-jdk-alpine`

**Comment by ccmjga** [comment]
2.7.2 版本全部替换为以下 jdk 镜像
https://github.com/ccmjga/mjga-scaffold/issues/7
