### ISSUE TITLE
jdk17 image for MacOS Apple silicon

### ISSUE THREAD

**Issue by TonyJiangWJ** [ccmjga/mjga-scaffold#7]
**Your OS & Cpu Architecture**
MacOS/arm64

**Soft Version**
2.7+

**Your template name**
Database First

**Describe the bug**
1. jdk17版本默认的docker镜像源不支持arm64 仅仅jdk21的支持 需要替换成其他的tag。
- <img width="789" alt="image" src="https://github.com/user-attachments/assets/51d6a06b-249a-4070-83b0-274f976ae498">
- 我这边找了一个 [17-jdk-noble](https://hub.docker.com/_/eclipse-temurin/tags?name=17-jdk-noble) 是支持多平台的，但是当在配置的时候选择了时区后Dockerfile本身还需要替换，因为这个内核是Ubuntu的不支持通过apk安装tzdata. 直接删除 `apk add -q tzdata && \` 就行

**Expected behavior**
不过上述镜像有几个漏洞，作者可以按上述截图中的描述信息，通过dockerhub查找合适的且多平台的镜像，进行替换，同时修改一下Dockerfile避免不支持特定系统的安装命令。

**Others**

**Comment by ccmjga** [comment]
已经确认了这个 bug，下个版本考虑用贝尔实验室的这个镜像
![image](https://github.com/user-attachments/assets/7c966125-88dc-48b4-bdfd-c9375b17c977)

https://hub.docker.com/layers/bellsoft/liberica-openjdk-alpine/17/images/sha256-051ff75690d6289731b761006133e74e71f06e2ba72559eb3cad0ab0fbb7b887?context=explore

看起来是支持 arm64 架构的。由于我没有 m 芯片的电脑，你这边介意用这个镜像测试一下吗？贝尔实验室的这个镜像看起来应该比 noble 更加可靠一点。

**Comment by ccmjga** [comment]
2.7.2 版本已全部替换成 bellsoft/liberica-openjdk-alpine
