### ISSUE TITLE
官网操作说明优化建议

### ISSUE THREAD

**Issue by TonyJiangWJ** [ccmjga/mjga-scaffold#8]
在第一步修改.env的那里增加修改gradle.properties的描述，因为这两个地方都涉及到对数据库配置的修改，如果只修改了.env会导致build的时候执行 jooqCodegen 失败

**Comment by ccmjga** [comment]
- (可选)在本机启动 
- 编译项目，并根据数据库 Schema 生成表的映射对象与 Data Access Layer

上面两个条目会增加 gradle.properties 的编辑描述

**Comment by ccmjga** [comment]
2.7.2 fixed
